### ISSUE TITLE
Time Range not getting selected when we include 12Am

### ISSUE THREAD

**Issue by hadi7khan** [Chris1234567899/flutter_time_range_picker#36]
If we include 12Am from label it is not working properly. For example if i pick a range from 10pm/22 to 1am it is not working, gives wrong time interval. If i disable the time 12am to lets say 2. Everything is working fine. Please fix this issue as soon as possible.

**Comment by Chris1234567899** [comment]
Please elaborate, what you mean. I could not find any issue, but maybe I did not understand your problem correctly.

**Comment by hadi7khan** [comment]
if i select a time range for a day (e.g 6th of july). if i select time range from 10pm to 1am it is not working because at 12 am next day starts( that will be 7th of july but i selected 6th of july only). Either you should not let users choose a time range from pm to am because it will be confusing.

**Comment by Chris1234567899** [comment]
If you set the start time to 10pm and the end time to 1am, you should get exactly this result:
A TimeRange  with start set to 10pm and end to 1am
It does not matter that it's another day. This picker only cares about time, dates are not covered. It's up to you to interprete the results in your code and choose a date according to your app logic.
Something like:
if endTime < startTime
  endDate.add(1,'days')
  
Did this answer your question?
Otherwise I'd recommend you post your code snippet either here or on stackoverflow.

**Comment by hadi7khan** [comment]
Thanks, yeah my question is answered now.
